= Fireworks

== 火枪手名字的由来

小的时候看过一个动漫《三个火枪手》，根据大仲马同名小说改编的。有个场面非常感人，几个火枪手一起举剑起誓，“人人为我，我为人人”。希望可以传承这种精神，相互帮助，相互学习，共同进步！所以就取了这个名字。

== 宗旨

火枪手帮带计划是一个公益行动，需要参与人缴纳任何费用。有收获，也要有付出。只有一个要求，参与者在大三以后也要带两个师弟或者师妹，帮忙他们解答学习疑问，指点学习方向。**人人为我，我为人人**，这就是我们的宗旨。希望各位参与者可以薪火传递。

== 学习任务


. **学会 https://haoel.github.io/[科学上网]。** -- 必做任务。穿越长城，走向世界。
. **学好英语，直接看英文原版资料。** -- 必做任务。希望各位参与者每天抽出一个小时时间来学习英语。最好听说读写全面提高。**真正的墙，并不是 GFW，而是语言。**当面对众多优质英文资料却读不懂，看不会，那才是悲剧。
. **爱祖国，上 https://www.google.com/[Google]。** -- 必备技能。
. **搜索程序相关问题， https://stackoverflow.com/[Stack Overflow] 是第一选择。** -- 必备技能。不夸张地说，没有 Stack Overflow 解答不了的技术问题。
. **百科只认 https://en.wikipedia.org/[Wikipedia]。** -- 解释更全面，内容更全面，更新更及时。
. **必须学会使用 https://github.com/[GitHub]。** -- 必做任务。希望把大学的代码都放到 GitHub 上。
. **到毕业为止刷够500道 https://leetcode.com/problemset/all/[LeetCode] 题。** -- 非硬性要求。考虑到目前招聘企业都面算法题，自己掂量。**注意：一定要是用英文网站。**
. **推荐学习一个轻量级标记语言。** -- 非硬性要求。不过，好处多多，谁用谁知道。
.. https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference] -- 强烈推荐学习 AsciiDoctor。在增加稍许的复杂度的情况下，功能更加强大。工具链也更加完整。
.. https://www.markdownguide.org/basic-syntax/[Markdown Guide] -- 可以说是随着 GitHub 而发扬光大的，GitHub 对其支持的非常好。在 Issue，README 等各方面都可以使用。
. **学习一门技术请认准官方文档，先通读一遍官方文档再说。** -- 学习中遇到的很多问题，基本在官方文档中都有介绍，看官方文档虽然略慢，但是大巧若拙。另外，大多数技术都起源于美国。所以，学好英文，看英文原版资料是基础技能。
. **刷论坛，看文章，优先选择 https://medium.com/[Medium]。** -- 一个非常好的社区。请科学上网。
. **看书首选经典。** -- 由于很多因素，导致学校在给学生购买教程时，往往选的都是垃圾。所以，在教程之外，推荐在购买一本经典书相辅。选书就上 https://book.douban.com/[豆瓣读书]，评分在八分以上就是好书，在九分以上就是神书。



== 学习方法

在学习某个技术的时候，除了会用到的知识图，还会问自己很多个为什么。于是，就形成了一个更高层的知识脑图。下面把这个学习方法或者学习模板分享出来。当然学习一门技术时，Go 语言也好，Docker 也好，只有把这个学习模板中的内容都填实了，才善罢甘休。这个模板如下：

. **这个技术出现的背景、初衷和要达到什么样的目标或是要解决什么样的问题。**这个问题非常关键，也就是说，你在学习一个技术的时候，需要知道这个技术的成因和目标，也就是这个技术的灵魂。如果不知道这些的话，那么你会看不懂这个技术的一些设计理念。
. **这个技术的优势和劣势分别是什么，或者说，这个技术的 trade-off 是什么。**任何技术都有其好坏，在解决一个问题的时候，也会带来新的问题。另外，一般来说，任何设计都有 trade-off（要什么和不要什么），所以，你要清楚这个技术的优势和劣势，以及带来的挑战。
. **这个技术适用的场景。**任何技术都有其适用的场景，离开了这个场景，这个技术可能会有很多槽点，所以学习技术不但要知道这个技术是什么，还要知道其适用的场景。没有任何一个技术是普适的。注意，所谓场景一般分别两个，一个是业务场景，一个是技术场景。
. **技术的组成部分和关键点。**这是技术的核心思想和核心组件了，也是这个技术的灵魂所在了。学习技术的核心部分是快速掌握的关键。
. **技术的底层原理和关键实现。**任何一个技术都有其底层的关键基础技术，这些关键技术很有可能也是其它技术的关键基础技术。所以，学习这些关键的基础底层技术，可以让你未来很快地掌握其它技术。可以参看我在 CoolShell 上写的 Docker 底层技术那一系列文章。
. **已有的实现和它之间的对比。**一般来说，任何一个技术都会有不同的实现，不同的实现都会有不同的侧重。学习不同的实现，可以让你得到不同的想法和思路，对于开阔思维，深入细节是非常重要的。

基本上来说，如果按照上面所提的这 6 大点来学习一门技术，一定会学习到技术的精髓，而且学习的高度在一开始就超过很多人了。如果能这样坚持 2-3 年，相信一定会在某个领域成为炙手可热的佼佼者。

TIP: 摘自 http://gk.link/a/1009i[左耳朵耗子的专栏“左耳听风”]。这是“极客时间”上含金量最高的专栏。推荐购买。（点击这个链接购买有优惠。）